version: "2"
#
# Services
#
services:
  postgresdb:
    build: ./docker/postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432
    networks:
        - localnet


# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true